# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

image: python:alpine

before_script:
  - apk add --no-cache git
  - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple mkdocs && mkdocs --version
  - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple mkdocs-material
  - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple mkdocs-glightbox
  - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple mkdocs-git-revision-date-localized-plugin
  - pip install git+https://github.com/pikvm/markdown-include

pages:
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
