site_name: OPiKVM
site_author: Floyde.lcy
copyright: Copyright &copy; 2023-2025 Floyde.lcy
site_url: https://opikvm.github.io/opikvm

repo_name: OPiKVM
repo_url: https://github.com/floydelcy/kvmd/tree/kvmd-rockchip
edit_uri: ""

theme:
  language: zh
  name: material
  palette:
    scheme: default
    primary: orange
    accent: indigo
  features:
    # - header.autohide
    # - navigation.footer
    # - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.expand
    # - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    # - toc.integrate

  logo: _assets/logo.svg
  favicon: _assets/favicon.png
  font:
    text: Montserrat
    code: JetBrains Mono
  custom_dir: overrides

# extra_css:
#     - _assets/user.css

extra_javascript:
    - '_assets/js/busuanzi.pure.mini.js'

plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: false
      draggable: true
      auto_caption: false
      caption_position: bottom
  - search:
      lang:
        - zh
      separator: '[\s\u200b\-]'
  - git-revision-date-localized:
      enable_creation_date: true
      timezone: Asia/Shanghai
      type: date
      locale: zh

markdown_extensions:
    - admonition
    - def_list
    - attr_list
    - pymdownx.tilde
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.magiclink
    - pymdownx.tabbed:
        alternate_style: true
    - md_in_html
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - markdown_include.include:
        base_path: docs

nav:
  - "简介": index.md
  - "使用手册":
    - "OPiKVM CM4 手册": CM4.md
  - "功能指南":
    - "如何接入网络": network.md
    - "配置指南": config.md
    - "系统更新": upgrade.md
    - "Web UI": webui.md
    - "身份验证以及2FA验证": auth.md
    - "视频模式": video.md
    - "音频/麦克风": audio.md
    - "ATX控制板": atx_board.md
    - "USB 设备配置" : usb.md
    - "设备标识(PID,VID,EDID)": id.md
    - "MSD大容量存储驱动器": msd.md
    - "模拟U盘/文件传输": simUSB.md
    - "模拟USB网卡/RDP代理": usb_ethernet.md
    - "更换SD卡": card2msd.md
    - "Tailscale VPN": tailscale.md
    - "连接WIFI": wifi.md
    - "设置静态IP地址": staticip.md
    - "串口服务器": USBserial.md
  - "进阶用法": advanced.md